language: python
os: linux
sudo: enabled

notifications:
  email: false

python:
  - "2.7"

install:
- sudo apt-get update -qq
#- sudo apt-get build-dep python-pygame
# - sudo apt-get install python-dev
# - sudo apt-get install python3 -y
# - sudo apt-get install python3-pip

# - sudo pip3 install pygame
# - sudo apt-get install -y software-properties-common
# - sudo add-apt-repository -y ppa:thopiekar/pygame
- sudo apt-get update -y
# - sudo apt-get install -y python3-pygame

- pip install pyaml
- pip install pygame

script:
  - find -iregex '.*[а-я].*' | wc -l | perl -lnwe 'die(q/No russian symbols in the project!/) if ($_ > 0)'
  - python2.7 tests/test.py

# after_success:
#   - python -m unittest tests/test_something.py
